### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by ghost** [JensKrumsieck/Catalyst#3]
Hello.
So I tried running the imgui example on a Mac but I got this error:
`Unhandled exception. System.InvalidOperationException: Attempted to initialize a Vulkan window using GLFW, which doesn't support Vulkan on this computer.`
Is there support for macOS or not?

**Comment by JensKrumsieck** [comment]
In theory it should support macOS, although i can not test it.
Windowing functionality is used without changes from the Silk.NET packages. 
Vulkan needs special options set when using macOS which according to the docs i set all to the correct value.

Did you get any other information than the error message?

**Comment by ghost** [comment]
Thanks for your reply!
So this was the entire console output I got:
`kian.schmalzl@MacBook-Air-von-Kian testproj % dotnet run
Unhandled exception. System.InvalidOperationException: Attempted to initialize a Vulkan window using GLFW, which doesn't support Vulkan on this computer.
   at Silk.NET.Windowing.Glfw.GlfwWindow.CoreInitialize(WindowOptions opts)
   at Silk.NET.Windowing.Internals.WindowImplementationBase.CoreInitialize(ViewOptions opts)
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Microsoft.Extensions.DependencyInjection.DependencyInjectionExtensions.AddWindow(ServiceCollection collection, ApplicationSpecification opts)
   at Program.<Main>$(String[] args) in /Users/kian.schmalzl/dev/projects/testproj/Program.cs:line 14
kian.schmalzl@MacBook-Air-von-Kian testproj % `
I hope this helps
